# Generated by Django 5.2.16 on 2026-08-13 13:09

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("products", "0001_initial"),
        ("vendors", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Report",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                (
                    "reason",
                    models.CharField(
                        choices=[
                            ("PROHIBITED_ITEM", "Prohibited Item"),
                            ("MISLEADING_LISTING", "Misleading Listing"),
                            ("SCAM_OR_FRAUD", "Scam or Fraud"),
                            ("INAPPROPRIATE_BEHAVIOR", "Inappropriate Behavior"),
                            ("FAKE_VENDOR", "Fake Vendor"),
                            ("OTHER", "Other"),
                        ],
                        max_length=30,
                    ),
                ),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("UNDER_REVIEW", "Under Review"),
                            ("RESOLVED", "Resolved"),
                            ("REJECTED", "Rejected"),
                        ],
                        db_index=True,
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                ("resolution_notes", models.TextField(blank=True, null=True)),
                (
                    "product",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reports",
                        to="products.product",
                    ),
                ),
                (
                    "reporter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reports_filed",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "resolved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reports_resolved",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "vendor_profile",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reports",
                        to="vendors.vendorprofile",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("product__isnull", False),
                                ("vendor_profile__isnull", True),
                            ),
                            models.Q(
                                ("product__isnull", True),
                                ("vendor_profile__isnull", False),
                            ),
                            _connector="OR",
                        ),
                        name="report_exactly_one_target",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(("reason", "OTHER"), _negated=True),
                            models.Q(
                                ("description__isnull", False),
                                models.Q(("description", ""), _negated=True),
                            ),
                            _connector="OR",
                        ),
                        name="report_other_reason_requires_description",
                    ),
                ],
            },
        ),
    ]
